---
repositories:
  - name: devopscorner-adot
    url: s3://devopscorner-adot-chart/prod

templates:
  default: &default
    namespace: devopscorner
    version: "1.4.0"

releases:
  - name: bookstore-adot
    chart: devopscorner-adot/api
    values:
      - ./api-rest-values.yml
    <<: *default
