version: 0.2

env:
  # ==================== #
  #  Ref: SECRET CONFIG  #
  # ==================== #
  parameter-store:
    BUILDNUMBER: /devopscorner/cicd/staging/repo/bookstore-adot/buildnumber
    STORE_AWS_ACCOUNT: /devopscorner/cicd/staging/credentials/aws_account
    STORE_AWS_ACCESS_KEY: /devopscorner/cicd/staging/credentials/aws_access_key
    STORE_AWS_SECRET_KEY: /devopscorner/cicd/staging/credentials/aws_secret_key
    STORE_REPO_URL: /devopscorner/cicd/staging/repo/bookstore-adot/url
    STORE_REPO_BRANCH: /devopscorner/cicd/staging/repo/bookstore-adot/branch
    STORE_REPO_FOLDER: /devopscorner/cicd/staging/repo/bookstore-adot/folder
    STORE_EKS_CLUSTER: /devopscorner/cicd/staging/eks_cluster
    STORE_BASE64_PUB_KEY: /devopscorner/cicd/staging/credentials/base64_pub_key
    STORE_BASE64_PRIV_KEY: /devopscorner/cicd/staging/credentials/base64_priv_key
    STORE_BASE64_PEM_KEY: /devopscorner/cicd/staging/credentials/base64_pem_key
    STORE_BASE64_SSH_CONFIG: /devopscorner/cicd/staging/credentials/base64_ssh_config
    STORE_BASE64_KNOWN_HOSTS: /devopscorner/cicd/staging/credentials/known_hosts
    STORE_BASE64_KUBECONFIG: /devopscorner/cicd/staging/credentials/base64_kube_config

  # ===================================== #
  #  Ref: Pipeline Environment Variables  #
  # ===================================== #
  variables:
    ENV_CICD: "dev"
    AWS_DEFAULT_REGION: "us-west-2"
    INFRA_CICD: "terraform/environment/providers/aws/infra/resources"
    INFRA_RESOURCES_TERRAFORM: "opensearch"
    INFRA_CICD_PATH: "bookstore-adot"
    INFRA_ECR_PATH: "devopscorner/bookstore-adot"

phases:
  build:
    commands:
      # ========================= #
      #  Refactoring AWS Account  #
      # ========================= #
      - cd ${CODEBUILD_SRC_DIR} && find ./ -type f -exec sed -i "s/YOUR_AWS_ACCOUNT/${STORE_AWS_ACCOUNT}/g" {} \;
      # =========================== #
      #  Install Terraform Modules  #
      # =========================== #
      - make codebuild-modules
      - cd ${CODEBUILD_SRC_DIR}/${INFRA_RESOURCES}/${INFRA_RESOURCES_TERRAFORM}
      # ========================= #
      #  Terraform Plan (Review)  #
      # ========================= #
      - terraform init
      - terraform workspace select ${WORKSPACE_ENV} || terraform workspace new ${WORKSPACE_ENV}
      - terraform plan --out tfplan.binary
      - terraform show -json tfplan.binary > tfplan.json
      # ================== #
      #  Terraform Addons  #
      # ================== #
      # ~ Terrascan ~
      - terrascan init
      - terrascan scan -o human
      # ~ Tfsec ~
      - tfsec .
      # ~ Checkov
      - checkov -f tfplan.json
      # ~ Infracost
      - infracost breakdown --path tfplan.json
      # ======================== #
      #  Terraform Provisioning  #
      # ======================== #
      - terraform apply -auto-approve
artifacts:
  files:
    - _infra/*
    - .aws/*
    - docs/*
    - src/*
    - dockerhub-build.sh
    - dockerhub-push.sh
    - dockerhub-tag.sh
    - ecr-build.sh
    - ecr-push.sh
    - ecr-tag.sh
    - Makefile
    - tfplan.binary
    - tfplan.json
  name: "artifact-$(date '+%Y%m%d-%H%M%S')"